In [21]:
import pandas as pd
import numpy as np

In [22]:
data = np.random.randn(4,3)

In [23]:
data

array([[ 0.09237562,  0.47473493,  0.01439977],
       [ 0.50726325, -0.19295015,  0.33923273],
       [ 0.28613109,  1.81192598, -0.7812271 ],
       [ 0.43829544, -0.74103191, -0.707283  ]])

In [24]:
data_frame = pd.DataFrame(data)

In [25]:
data_frame

          0         1         2
0  0.092376  0.474735  0.014400
1  0.507263 -0.192950  0.339233
2  0.286131  1.811926 -0.781227
3  0.438295 -0.741032 -0.707283

In [26]:
new_df = pd.DataFrame(data, index=["Atil","Zeynep","Atlas","Mehmet"], columns=["Salary","Age","Seniority"])

In [27]:
new_df

          Salary       Age  Seniority
Atil    0.092376  0.474735   0.014400
Zeynep  0.507263 -0.192950   0.339233
Atlas   0.286131  1.811926  -0.781227
Mehmet  0.438295 -0.741032  -0.707283

In [28]:
new_df["Age"]

Atil      0.474735
Zeynep   -0.192950
Atlas     1.811926
Mehmet   -0.741032
Name: Age, dtype: float64

In [29]:
new_df["Salary"]

Atil      0.092376
Zeynep    0.507263
Atlas     0.286131
Mehmet    0.438295
Name: Salary, dtype: float64

In [30]:
new_df[["Salary","Age"]]

          Salary       Age
Atil    0.092376  0.474735
Zeynep  0.507263 -0.192950
Atlas   0.286131  1.811926
Mehmet  0.438295 -0.741032

In [31]:
new_df.loc["Atil"]

Salary       0.092376
Age          0.474735
Seniority    0.014400
Name: Atil, dtype: float64

In [32]:
new_df.iloc[1]

Salary       0.507263
Age         -0.192950
Seniority    0.339233
Name: Zeynep, dtype: float64

In [33]:
new_df

          Salary       Age  Seniority
Atil    0.092376  0.474735   0.014400
Zeynep  0.507263 -0.192950   0.339233
Atlas   0.286131  1.811926  -0.781227
Mehmet  0.438295 -0.741032  -0.707283

In [34]:
new_df.iloc[:,2] # : -> tüm rowları getir, 2 -> 2.index(sütun)

Atil      0.014400
Zeynep    0.339233
Atlas    -0.781227
Mehmet   -0.707283
Name: Seniority, dtype: float64

In [35]:
new_df["Age"]

Atil      0.474735
Zeynep   -0.192950
Atlas     1.811926
Mehmet   -0.741032
Name: Age, dtype: float64

In [36]:
new_df["Extra"] = 10

In [37]:
new_df

          Salary       Age  Seniority  Extra
Atil    0.092376  0.474735   0.014400     10
Zeynep  0.507263 -0.192950   0.339233     10
Atlas   0.286131  1.811926  -0.781227     10
Mehmet  0.438295 -0.741032  -0.707283     10

In [38]:
new_df.drop("Extra", axis=1, inplace=True) # axis=1 -> sütun, axis=0 -> satır inplace ise bu işlemi bu değişkene uygula demektir.
# inplace kullanılmazsa bir kopyasını gösterir. Gerçeğine uygulamaz.

In [39]:
new_df

          Salary       Age  Seniority
Atil    0.092376  0.474735   0.014400
Zeynep  0.507263 -0.192950   0.339233
Atlas   0.286131  1.811926  -0.781227
Mehmet  0.438295 -0.741032  -0.707283

In [41]:
new_df[new_df["Age"] > 0]

         Salary       Age  Seniority
Atil   0.092376  0.474735   0.014400
Atlas  0.286131  1.811926  -0.781227

In [44]:
new_df[new_df["Age"] > 0 ]

         Salary       Age  Seniority
Atil   0.092376  0.474735   0.014400
Atlas  0.286131  1.811926  -0.781227

In [49]:
new_df

          Salary       Age  Seniority  (Atlas, Salary)
Atil    0.092376  0.474735   0.014400              100
Zeynep  0.507263 -0.192950   0.339233              100
Atlas   0.286131  1.811926  -0.781227              100
Mehmet  0.438295 -0.741032  -0.707283              100

In [58]:
new_df.loc["Atlas","Salary"] = 100

In [59]:
new_df

            Salary       Age  Seniority
Atil      0.092376  0.474735   0.014400
Zeynep    0.507263 -0.192950   0.339233
Atlas   100.000000  1.811926  -0.781227
Mehmet    0.438295 -0.741032  -0.707283

In [60]:
new_df.reset_index()

    index      Salary       Age  Seniority
0    Atil    0.092376  0.474735   0.014400
1  Zeynep    0.507263 -0.192950   0.339233
2   Atlas  100.000000  1.811926  -0.781227
3  Mehmet    0.438295 -0.741032  -0.707283

In [61]:
reset_frame = new_df.reset_index()

In [63]:
reset_frame.loc[0]

index            Atil
Salary       0.092376
Age          0.474735
Seniority      0.0144
Name: 0, dtype: object

In [64]:
new_indices = ["Ati","Zey","Atl","Meh"]

In [65]:
new_df["NewIndex"] = new_indices

In [66]:
new_df

            Salary       Age  Seniority NewIndex
Atil      0.092376  0.474735   0.014400      Ati
Zeynep    0.507263 -0.192950   0.339233      Zey
Atlas   100.000000  1.811926  -0.781227      Atl
Mehmet    0.438295 -0.741032  -0.707283      Meh

In [68]:
new_df.set_index("NewIndex", inplace=True)

In [69]:
new_df

              Salary       Age  Seniority
NewIndex
Ati         0.092376  0.474735   0.014400
Zey         0.507263 -0.192950   0.339233
Atl       100.000000  1.811926  -0.781227
Meh         0.438295 -0.741032  -0.707283

In [71]:
new_df.loc["Ati"]

Salary       0.092376
Age          0.474735
Seniority    0.014400
Name: Ati, dtype: float64

In [72]:
# multi index

In [73]:
first_index = ["Simpson","Simpson","Simpson", "South Park", "South Park", "South Park"]

In [74]:
inner_index = ["Homer","Bart","Marge","Cartman","Kenny","Kyle"]

In [75]:
zipped_index = list(zip(first_index, inner_index))

In [79]:
zipped_index

[('Simpson', 'Homer'),
 ('Simpson', 'Bart'),
 ('Simpson', 'Marge'),
 ('South Park', 'Cartman'),
 ('South Park', 'Kenny'),
 ('South Park', 'Kyle')]

In [80]:
zipped_index = pd.MultiIndex.from_tuples(zipped_index)

In [81]:
zipped_index

MultiIndex([(   'Simpson',   'Homer'),
            (   'Simpson',    'Bart'),
            (   'Simpson',   'Marge'),
            ('South Park', 'Cartman'),
            ('South Park',   'Kenny'),
            ('South Park',    'Kyle')],
           )

In [82]:
sample_values = np.ones((6, 2))

In [83]:
big_df = pd.DataFrame(sample_values, index=zipped_index, columns=["Age", "Salary"])

In [84]:
big_df

                    Age  Salary
Simpson    Homer    1.0     1.0
           Bart     1.0     1.0
           Marge    1.0     1.0
South Park Cartman  1.0     1.0
           Kenny    1.0     1.0
           Kyle     1.0     1.0

In [85]:
big_df["Age"]

Simpson     Homer      1.0
            Bart       1.0
            Marge      1.0
South Park  Cartman    1.0
            Kenny      1.0
            Kyle       1.0
Name: Age, dtype: float64

In [89]:
big_df.loc["Simpson"].loc["Homer"]

Age       1.0
Salary    1.0
Name: Homer, dtype: float64